name: Python Informer

on: 
  [push]
jobs:
  Daily-Run:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: install python packages
        run:
          pip install -r requirements.txt
      - name: Run App
        run: python main.py